name: tests
on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: Python ${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.instructions }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        instructions:
          - avx
          - avx2
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.x'
        exclude:
          - os: macos-latest
            instructions: avx2

    steps:
      - uses: actions/checkout@v3

      - id: cache-model
        uses: actions/cache@v3
        with:
          path: ggml-gpt4all-j.bin
          key: ggml-gpt4all-j.bin

      - name: Download Model
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: curl -sOL https://gpt4all.io/models/ggml-gpt4all-j.bin

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test
        run: pytest tests --instructions ${{ matrix.instructions }}
